# Generated by Django 4.2.8 on 2024-04-15 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='excerpt',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='provider',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='article',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='article',
            name='url',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.TextField(default=''),
        ),
    ]
