version: '3.8'

services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "7860:7860"
    environment:
      - DATABASE_URL=sqlite:///db.sqlite3

  frontend:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    command: sh -c "npm install --silent && npm start"

  storybook:
    image: node:18
    working_dir: /app
    volumes:
      - ./frontend:/app
    ports:
      - "6006:6006"
    command: sh -c "npm install --silent && npm run storybook"
