#!/bin/bash

show_help() {
    echo "Usage: ./script/test [frontend|backend|ci]"
    echo ""
    echo "Commands:"
    echo "  frontend  - Run the tests for the frontend, watching for changes"
    echo "  backend   - Run the tests for the backend, watching for changes"
    echo "  ci        - Run the tests once for frontend and backend"
}

case "$1" in
    frontend)
        echo "Running and watching frontend tests..."
        docker-compose exec frontend npm run test
        ;;
    backend)
        echo "Running and watching backend tests..."
        docker-compose exec backend ptw
        ;;
    ""|ci)
        echo "Running tests..."
        docker-compose exec frontend npm run test:ci
        docker-compose exec backend pytest
        ;;
    *)
        echo "Unexpected input: $1"
        show_help
        ;;
esac
